name: Validate and Checksum

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run validation script
        run: |
          python validate.py  # Run your validation and checksum calculation script

      - name: Commit and push result.json
        run: |
          git add result.json
          git commit -m "Update result.json with checksum"
          git push

